# Generated by Django 4.2.4 on 2023-08-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=55)),
                ('lastname', models.CharField(max_length=55)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=55)),
            ],
        ),
    ]
