# Generated by Django 4.2.4 on 2023-08-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newormapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
